import Head from 'next/head'
import Image from 'next/image'
import { Inter, Irish_Grover } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useUser } from '@auth0/nextjs-auth0/client'
import { useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { user, error, isLoading } = useUser();
  const [url, setURL] = useState('/api/auth/login')
  const [button, setButton] = useState('Login')

  useEffect(() => {
    if (typeof user !== 'undefined') {
      setButton('Logout')
      setURL('/api/auth/logout')
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Play0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="hero min-h-screen bg-base-200">
          <div className="hero-content text-center">
            <div className="max-w-md">
              <h1 className="text-5xl font-bold">PlayO</h1>
              <p className="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
              <button className="btn btn-primary"><a href={url}>{button}</a></button>
              {user && (<><button className="btn btn-primary"><a href="/feed/">Check Feed</a></button></>)}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
